name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build plugin
        run: npm run build
      
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          body: |
            ## CF7 Custom Validation Messages v${{ steps.get_version.outputs.VERSION }}
            
            ### Installation
            1. Download the ZIP file below
            2. Go to WordPress Admin → Plugins → Add New → Upload Plugin
            3. Upload the ZIP file and activate
            
            ### Requirements
            - WordPress 6.7 or higher
            - PHP 7.4 or higher
            - Contact Form 7 (latest version)
            
            See [CHANGELOG.md](https://github.com/halfcoder/cf7-custom-validation-messages/blob/main/CHANGELOG.md) for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

